### ISSUE TITLE
No way to set collapseMode in CollapsingToolbarLayout child

### ISSUE THREAD

**Issue by fboldog** [Kotlin/anko#153]
This is not possible at the moment:

``` kotlin
                collapsingToolbarLayout {
                    id = TOOLBAR_LAYOUT_ID
                    fitsSystemWindows = true

                    contentScrim = ColorDrawable(colorAttr(R.attr.colorPrimary))

                    toolbar(ThemeOverlay_AppCompat_Dark_ActionBar) {
                        id = TOOLBAR_ID
                        popupTheme = ThemeOverlay_AppCompat_Light
                    }.lparams(width = matchParent, height = dimenAttr(R.attr.actionBarSize)){
                        collapseMode = COLLAPSE_MODE_PIN
                    }
                }
```

This is the missing extension method:

``` kotlin
fun <T : android.view.View> T.lparams(
        width: kotlin.Int = wrapContent, height: kotlin.Int = wrapContent,
        init: android.support.design.widget.CollapsingToolbarLayout.LayoutParams.() -> kotlin.Unit = defaultInit): T {
    val layoutParams = android.support.design.widget.CollapsingToolbarLayout.LayoutParams(width, height)
    layoutParams.init()
    this@lparams.layoutParams = layoutParams
    return this
}
```

**Comment by rothso** [comment]
I ran into the same issue. I'm able to use @fboldog's workaround, but digging deeper it looks like all the children of CollapsingToolBar are using FrameLayout.LayoutParams instead of CollapsingToolBar.LayoutParams: e.g. [LayoutsTest.kt#L84](https://github.com/Kotlin/anko/blob/a92995071ef75c0fc104c6a0bbcf56598e9cec19/anko/library/testData/functional/design/LayoutsTest.kt#L84)

This would explain why children can't access CollapsingToolbarLayout's DSL. Trying to call any of these lparams also throws a nasty `ClassCastException`.

```kotlin
open class _CollapsingToolbarLayout(ctx: Context): android.support.design.widget.CollapsingToolbarLayout(ctx) {
    fun <T: View> T.lparams(
            c: android.content.Context?,
            attrs: android.util.AttributeSet?,
            init: android.widget.FrameLayout.LayoutParams.() -> Unit = defaultInit
    ): T {
        val layoutParams = android.widget.FrameLayout.LayoutParams(c!!, attrs!!)
        layoutParams.init()
        this@lparams.layoutParams = layoutParams
        return this
    }
    // ... and the others ...
```
It looks like all we need to do is just change the functions to use `CollapsibleToolbarLayout.LayoutParams`. I'll open a PR tonight if no one else gets to it.

**Comment by nomisRev** [comment]
Has anything happened here yet? Otherwise I'm willing to fix and PR this tomorrow.

**Comment by nomisRev** [comment]
@yanex I was unable to build the project. I tried AS and IDEA but without success. Neither dev or master. Also followed doc/building.md but without luck.

I think I have pinpointed the problem. In https://github.com/Kotlin/anko/blob/master/anko/library/generator/src/org/jetbrains/android/anko/generator/layoutParamsUtils.kt, you use the `generateLayoutParams` method to determine the LayoutParams from the return type but you should use `generateDefaultLayoutParams` since that one always return the correct LayoutParams.

For collapsing CollapsingToolbarLayout `generateLayoutParams` it returns `FrameLayout.LayoutParams` and thus does not accept any configuration for CollapsingToolbarLayout.

On a side note, if you could help me to build I'd be happy to fix this. And do some more contributing for 9.1 release.

**Comment by kengorab** [comment]
Has there been any work done to fix this issue yet?

**Comment by kirillkh** [comment]
This issue has been up for a year and a half now... Is Anko dead?

**Comment by alm494** [comment]
I broke my head

**Comment by kirillkh** [comment]
Haven't tried it yet, but thanks for fixing this!
