### ISSUE TITLE
Cannot use the AnkoComponent Interface.

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [Kotlin/anko#183]
When I have the following code:

    package com.example.xiaolong.kotlinapp

    import org.jetbrains.anko.AnkoComponent
    import org.jetbrains.anko.AnkoContext

    class MainActivityView : AnkoComponent {
        override fun createView(ui: AnkoContext) = with(ui) {
            verticalLayout {
                val name = editText()
                button("Say Hello") {
                    onClick {
                        ctx.toast("Hello, ${name.text}!")
                    }
                }
            }
        }
    }

in a Kotlin class file in Android Studio (AS) build 143.2790544, AS will underline the word `AnkoComponent` next to `MainActivityView` red. When I hover over it with the coursor, it'll show me a tool tip reading: `Type argument expected`.

In my `build.gradle (Module: app)` file I have the following content:

	apply plugin: 'com.android.application'
	apply plugin: 'kotlin-android'
	apply plugin: 'kotlin-android-extensions'

	android {
		compileSdkVersion 23
		buildToolsVersion "23.0.3"

		defaultConfig {
			applicationId "com.example.xiaolong.kotlinapp"
			minSdkVersion 21
			targetSdkVersion 23
			versionCode 1
			versionName "1.0"
		}
		buildTypes {
			release {
				minifyEnabled false
				proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			}
		}
		sourceSets {
			main.java.srcDirs += 'src/main/kotlin'
		}
	}

	dependencies {
		compile fileTree(dir: 'libs', include: ['*.jar'])
		testCompile 'junit:junit:4.12'
		compile 'com.android.support:appcompat-v7:23.3.0'
		compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
		compile 'org.jetbrains.anko:anko-sdk23:0.8.3' // sdk19, sdk21, sdk23 are also available
		compile 'org.jetbrains.anko:anko-support-v4:0.8.3' // In case you need support-v4 bindings
		compile 'org.jetbrains.anko:anko-appcompat-v7:0.8.3' // For appcompat-v7 bindings
	}
	buildscript {
		ext.kotlin_version = '1.0.1-2'
		repositories {
			mavenCentral()
		}
		dependencies {
			classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
			classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
		}
	}
	repositories {
		mavenCentral()
	}

So I added those compile dependencies and only changed to `sdk23`, which I guessed is newer and more up to date. Then I synchronized the project, as AS suggests when you change the gradle files. That worked without issues.

**Info**

* I have installed the Kotlin plugin version: updated 28th of March 2016, v1.0.1-release-IJ143-40
* AS version 143.2790544
* OS: Fedora 22

What am I doing wrong?

**Comment by Ribesg** [comment]
The example is outdated, you need to do exactly what AS says you should do: add a type.
In this case the type should be your `MainActivity` I guess. Setting this type will make you able to reach your `MainActivity` via `ui.owner`.

**Comment by ZelphirKaltstahl** [comment]
I don't understand where it wants me to add a type? Isn't AnkoComponent the type I want? It's supposed to be a View class, which designs the GUI using the DSL.

**Comment by krissrex** [comment]
Should look something like this
```kotlin
class MainActivityView : AnkoComponent<Activity> {
    override fun createView(ui: AnkoContext<Activity>) : View = with(ui) {
        return verticalLayout {
            val name = editText()
            button("Say Hello") {
                onClick {
                    ctx.toast("Hello, ${name.text}!")
                }
            }
        }
    }
}
```

**Comment by ZelphirKaltstahl** [comment]
@krissrex Thanks, that solves the red underlining. I think I have to take a deeper dive into Kotlin to understand that code though. I should probably take a more step by step apporach and first learn more Kotlin and then try to do some Android stuff with it. Otherwise it's too many new ways of writing things in a very compact way and it can be confusing.

**Comment by krissrex** [comment]
@ZelphirKaltstahl Alright. The [Koans](http://try.kotlinlang.org/#/Kotlin%20Koans/Introduction/Hello,%20world!/Task.kt) are great for learning kotlin.

I could try to explain it a litte. The ```AnkoComponent<Activity>``` wants you to implement a function ```createView``` that returns a ```View```. Its parameter is an ```AnkoContext<Activity>``` named ```ui```

```kotlin
interface AnkoComponent<Activity> {
    fun createView(ui: AnkoContext<Activity>) : View 
}
```

We implement it using ```with(ui)```, so we can act on ```ui``` as if we wrote code inside the ```AnkoContext<Activity>``` class.

```kotlin
class MainActivityView : AnkoComponent<Activity> {
    override fun createView(ui: AnkoContext<Activity>) : View = with(ui) {
    
    }
}
```

[With](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/with.html) looks like this:

```kotlin
inline fun <T, R> with(receiver: T, block: T.() -> R): R
```

That is, a function named ```with``` that takes in an object named reciever (for us, it is ```ui``` and the type template ```T``` is ```AnkoContext<Activity>```), and an [extension function](https://kotlinlang.org/docs/reference/extensions.html#extension-functions) named ```block```.
It extends ```T``` (which is ```AnkoContext<Activity>```), and returns ```R```. ```R``` is of type ```View```, which is deduced from what the function ```createView``` expects. 

For ```block``` we pass a [function](https://kotlinlang.org/docs/reference/lambdas.html#higher-order-functions) with the following code:

```kotlin
return verticalLayout {
            val name = editText()
            button("Say Hello") {
                onClick {
                    ctx.toast("Hello, ${name.text}!")
                }
            }
        }
```

Note that we are using the following convention: 

> In Kotlin, there is a convention that if the last parameter to a function is a function, that parameter can be specified outside of the parentheses

which is why you don't see ```block``` being passed in to ```with``` after ```ui```. The same convention is being used by anko for ```verticalLayout``` (from [CustomViews line 56](https://github.com/Kotlin/anko/blob/master/anko/library/static/platform/src/CustomViews.kt)):

```kotlin
inline fun Activity.verticalLayout(theme: Int = 0, init: _LinearLayout.() -> Unit): LinearLayout {
    return ankoView(`$$Anko$Factories$CustomViews`.VERTICAL_LAYOUT_FACTORY, theme, init)
}
```

where ```init``` contains this code that we wrote:

```kotlin
val name = editText()
button("Say Hello") {
    onClick {
            ctx.toast("Hello, ${name.text}!")
     }
 }
```

So, to conclude: ```createView``` is a function that takes in ```ui``` and returns a ```verticalLayout```. The ```verticalLayout``` is constructed inside ```ui``` with an *extension function* and *with*.

I hope that cleared it up a little. And if anyone spots any mistakes, tell me and I'll fix them :sweat_smile:
