### ISSUE TITLE
[question] layout for AppWidgetProvider

### ISSUE THREAD

**Issue by kufii** [Kotlin/anko#247]
I'm trying to make a widget for my app, and I want to avoid making any xml layouts.
To update the widget you have to call appWidgetManager.updateAppWidget which takes an object of RemoteViews. The RemoteViews constructor takes an xml layout id. Is there a way to create this RemoteViews object without using a layout id and using the Anko DSL instead?

**Comment by LouisCAD** [comment]
There's no `RemoteViews` constructor which takes a `View`, but only layout resource id, so it's not possible. The response is in Android API itself, and RemoteViews don't accept objects because the layout will be displayed by another app (launcher or SystemUI) while your app is not in the VM (killed).

**Comment by kufii** [comment]
Ok that makes sense
