### ISSUE TITLE
[Question] Passing context with `doAsync`

### ISSUE THREAD

**Issue by AllanWang** [Kotlin/anko#496]
A very common Android background task involves retrieving data  then updating the UI. In almost all cases, this involves a context. Say we have an Activity (which extends Context) that does the following:

```
doAsync {
    //run data
    uiThread {
        show(); //some function under activity
    }
}
```

Would this hold onto the activity reference, since it is needed to call `show`, which effectively renders the weak reference a strong reference?

We may also note that we can get the context from the `weakRef` inside `doAsync`. Is that necessary to ensure proper cancellation?

I just noticed that there was another method, `activityUiThread`. That may be the reason for some of my issues, but I'm curious if that's going to fix everything

**Comment by 1001101** [comment]
```
        anyObj.doAsync {
            // background thread.

            uiThread {
                with(it) {
                    //do something on UI thread.
                    //will not strong reference to anyObj here.

                }
            }
        }

```

**Comment by AllanWang** [comment]
@1001101 correct, but the key is that you used `with(it)`. What if someone doesn't do that by accident? (As I have until I've noticed it now). Would it not be better to have a redefined `uiThread` accepting `T.() -> Unit` vs `(T) -> Unit`?

**Comment by 1001101** [comment]
fun <T> AnkoAsyncContext<T>.onComplete(f: (T?) -> Unit) { ... }

**Comment by humazed** [comment]
I think you could use `activityUiThreadWithContext` as it takes `Context` as a receiver.

**Comment by gildor** [comment]
I'm not sure that answer from @1001101 is correct, because anyObj and uIThread lambda are captured by background thread lambda and will leak during ` // background thread.` invocation and dispatching

**Comment by gildor** [comment]
> Would this hold onto the activity reference, since it is needed to call show, which effectively renders the weak reference a strong reference?
Yes, to invoke activity method `show()` lambda has hard reference to activity

**Comment by AllanWang** [comment]
The comment here is that the `with` usage can be avoided entirely if the lambda was of type `Context.() -> Unit`. People may not be aware of the weak references, and if it really made a difference, then our usage without `it` would break everything.

**Comment by gildor** [comment]
There is no difference how you use some variable as `T.() -> Unit` or `(T) -> Unit` or just `T.doSomething()`, all those cases are exactly the same in terms of memory management. Things like `activityUiThreadWithContext` just a wrapper for weak reference.

Anyway, I wouldn't recommend using doAsync just because it doesn't work with cancellation and lifecycle. The only thing that you can do: use weak reference which is not perfect also can cause leaks (for example if this reference leaked to another code or even just saved to local variable)

**Comment by AllanWang** [comment]
The difference here is that people may not realize the weak reference exists, and then try to access `Context` directly. Making it an extension would make things more natural, as you can write code in an `Activity` as you would normally, and the context used would instead be that from the unwrapped weak reference. If you supply a user with a function `T.(T) -> Unit`, their intuition may not always lead them to use the parameter, especially since it is hidden within single arg lambda notation. This naturally doesn't solve the problem if you are in a view and choose to get contexts through `getContext()`.

Regardless, this was a comment I made a year ago, as weakreferences were things I glossed over for months before realizing it. I understand that I have pointed to this issue within the kotlin slack for clarifications of the necessity of weak references, but I think I'm clear on that now with the lifecycles. Given that anko does not enforce destruction in the lifecycle, it needs weak references. Coroutines on the other hand are expected to handle it from the parent job, and don't need the weak references.

**Comment by gildor** [comment]
@AllanWang 

> The difference here is that people may not realize the weak reference exists, and then try to access Context directly

I think the problem is much-much wider and you shouldn't focus on Context only, because capturing of the parent class (such as Activity) in lambda always cause at least temporary memory leak if your operation is not cancellable. In cases when you do not capture parent context, the compiler can avoid this implicit reference to parent class (which is not true if you use Java anonymous class which always keeps the implicit reference on parent class).

> Given that anko does not enforce destruction in the lifecycle, it needs weak references

Yes, this is correct, because doAsync is blocking and non-cancellable operation. And this is fatal, non-solvable problem,.
So I think we shouldn't talk about lambdas with receiver (`T.() -> Unit`) or about getContext(), because in case of blocking/non-cancellable operations you must use only weak references to avoid leaks and this is very tedious (even with helprs that Anko provides) and very error-prone.


So my suggestion would be the same as @1001101, use some abstraction/framework for asynchronous operations that provides cancellation and lifecycle management out of the box, such as RxJava or Kotlin Coroutines (which is even more strict in terms of lifecycle and scopes)

**Comment by huycn** [comment]
I'm not sure why this issue was closed but the problem described in initial post is still true for today, i.e.
```
class MyClass {
    fun show() {...}
    fun task() {
        doAsync {
            //run data
            uiThread {
                show(); //some function under activity
            }
        }
    }
}
```
will hold strong reference to MyClass, which prevent it from gabage-collected.

But if `uiThread` is modified so that it accepts `T.() -> Unit` as argument, it will work as expected, `MyClass` can be gabage-collected  before show() is called.

Yes, I agree that with current interface, `it.show()` instead just `show()` will also work, but we are talking about avoiding easy mistakes.

Also yes, we can use coroutines, but uiThread is still available and we can easily make mistake with it, even we are aware of the issue.
