### ISSUE TITLE
tabLayout.onTabSelectedListener{ } run ERROR

### ISSUE THREAD

**Issue by xinnuo** [Kotlin/anko#682]
when TabLayout add method onTabSelectedListener{ }, it operation crash.

**Comment by 3moeslam** [comment]
Can you add crash log

**Comment by xinnuo** [comment]
java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.ruanmeng.smart_parking-BO76hAaXXlKILy1CVIJXLw==/split_lib_dependencies_apk.apk)

**Comment by iceboundrock** [comment]
The `addOnTabSelectedListener ` method has been added since v26.1, so please make sure you use support library v26.1 or higher. See [this](https://developer.android.com/reference/android/support/design/widget/TabLayout.html#addOnTabSelectedListener(android.support.design.widget.TabLayout.OnTabSelectedListener))

**Comment by xinnuo** [comment]
Thank you. I already have a solution.

**Comment by iceboundrock** [comment]
Hi @xinnuo I am glad you resolved the problem, could you please close this issue? Thanks.

**Comment by xinnuo** [comment]
ok
