### ISSUE TITLE
Anko version needs to be a min of 15

### ISSUE THREAD

**Issue by digimbyte** [Kotlin/anko#706]
I am new to Android Development and following a tutorial that uses Anko, I came across an issue
`Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [org.jetbrains.anko:anko:0.10.8] C:\Users\digim\.gradle\caches\transforms-1\files-1.1\anko-0.10.8.aar\1497f6a6c03d28eedaa9c07d9d9b1668\AndroidManifest.xml as the library might be using APIs not available in 14
	Suggestion: use a compatible library with a minSdk of at most 14,
		or increase this project's minSdk version to at least 15,
		or use tools:overrideLibrary="org.jetbrains.anko.generated.anko" to force usage (may lead to runtime failures)
`
I have the following
`
    implementation "org.jetbrains.anko:anko:$anko_version"
    implementation "org.jetbrains.anko:anko-design:$anko_version"
    implementation "org.jetbrains.anko:anko-appcompat-v7-coroutines:$anko_version"`

and 
`
    ext.kotlin_version = '1.2.71'
    ext.anko_version = '0.10.8'`

should I use the Tools override? would it cause runtime errors? and if so, where do I put it?

**Comment by benibela** [comment]
I am porting an app from Java to Kotlin and thought Anko would help a lot, but then it did not compile due to this issue. Till this is resolved, I copied the functions I need [to my project](https://github.com/benibela/videlibri/blob/master/android/android/src/de/benibela/videlibri/UtilAnko.kt) that is the simplest solution. And I was already upset that I had to increase minSdk from 9 to 14 for the support library of

**Comment by 4u7** [comment]
When you create new project in Android Studio 3.2 `API 15` is selected by default and it says: "By targeting API 15 and later, your app will run on **100%** of devices"
