### ISSUE TITLE
lparams does not work for Activity

### ISSUE THREAD

**Issue by peleteiro** [Kotlin/anko#87]
```kotlin
public class MyActivity : Activity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    verticalLayout {
      verticalLayout {
        ...         
      }.lparams { // <--- works
          ...
      }
    }.lparams {}  // <--- does not
  }

}
```

**Comment by yanex** [comment]
In what case you need to set top-level layout parameters?

**Comment by peleteiro** [comment]
When I want to set margins/padding and when I want to extract parts of my UI to methods on the activity? I'm newbie on Anko, but I guess it's needed. At least, in my understand, layoutParams use to work.

**Comment by lukaspili** [comment]
Same problem here.
It's especially an issue when using Anko within a custom view, because you don't set a top-level layout.

**Comment by brolund** [comment]
I have the same problem. I need to set height=matchParent to avoid having empty space at the bottom of a page. 

Is there a compelling reason to treat top level elements differently? Since you actually can set layout parameters on a top level XML layout, it seems a bit strange not being able to do that in anko. 

Sure, I can probably hack around it, but since anko is so elegant otherwise, this seems very odd, and it took me a while to realize I wasn't doing anything wrong.

BTW, thanks for anko! Awesome initative!

**Comment by bkach** [comment]
@brolund Looks like the functionality you're looking already exists using lparams within the top level element.

For example:
```
        verticalLayout {

            lparams {
                width = matchParent
                height = matchParent
            }

...

}
```

**Comment by aneophyte** [comment]
That doesn't work. I applied margin explicitly, only that worked.
```kotlin
        verticalLayout {
            ...

        }.layoutParams = with(FrameLayout.LayoutParams(matchParent, matchParent)) {
            leftMargin = dip(16)
            rightMargin = dip(16)
            this
        }
```

**Comment by yanex** [comment]
Anko doesn't know what the layout is available on the top DSL level, so you obviously can't set it via `lparams`. Please use the `layoutParams` synthetic property (`setLayoutParams()` method) to set it in this case.

@aneophyte you can also use the `apply` function from **stdlib** so you don't have to explicitly return `this`.
